### ISSUE TITLE
​

### ISSUE THREAD

**Issue by ghost** [photonized/terra-toolbox-webapp#5]

**Comment by theodubiel** [comment]
True, I noticed that when I was looking at the contract on extraterrestrial.  I think you can pass in an array of idx to the contract and it will cancel them all.  I will add this to the contract hook.

Edit: To clarify, do you send an array of bid_idx in a single message, or do you send multiple messages in one transaction?

**Comment by yoonsung21** [comment]
> True, I noticed that when I was looking at the contract on extraterrestrial. I think you can pass in an array of idx to the contract and it will cancel them all. I will add this to the contract hook.
> 
> Edit: To clarify, do you send an array of bid_idx in a single message, or do you send multiple messages in one transaction?

multiple messages in one transaction. retract_bid transaction does not support array of indices I believe.
